on:
  pull_request:
    branches:
      - main

jobs:
  encode-and-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get changed blueprint folders
        id: changes
        run: |
          echo "folders=$(git diff --name-only ${{ github.event.pull_request.base.sha }} | grep '^blueprints/' | cut -d/ -f2 | sort -u | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

      - name: Generate base64 for changed blueprints only
        id: generate
        run: |
          CHANGED_FOLDERS=$(echo '${{ steps.changes.outputs.folders }}' | jq -r '.[]')

          echo "### 📝 Base64 for changed blueprints" > comment.md
          echo '' >> comment.md

          if [ -z "$CHANGED_FOLDERS" ]; then
            echo "✅ No blueprints changed." >> comment.md
          else
            echo "<details>" >> comment.md
            echo "<summary>🔍 Show base64</summary>" >> comment.md
            echo '' >> comment.md

            for dir in $CHANGED_FOLDERS; do
              TEMPLATE_NAME="$dir"
              COMPOSE_FILE="blueprints/$dir/docker-compose.yml"
              TEMPLATE_FILE="blueprints/$dir/template.yml"

              if [ -f "$COMPOSE_FILE" ] && [ -f "$TEMPLATE_FILE" ]; then
                COMPOSE_CONTENT=$(jq -Rs . < "$COMPOSE_FILE")
                TEMPLATE_CONTENT=$(jq -Rs . < "$TEMPLATE_FILE")

                JSON="{\"compose\":$COMPOSE_CONTENT,\"config\":$TEMPLATE_CONTENT}"
                BASE64_JSON=$(echo -n "$JSON" | base64 -w 0)

                echo "#### $TEMPLATE_NAME" >> comment.md
                echo '' >> comment.md
                echo '```' >> comment.md
                echo "$BASE64_JSON" >> comment.md
                echo '```' >> comment.md
                echo ''
              fi
            done

            echo '</details>' >> comment.md
          fi

      - name: Post comment to PR
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          path: comment.md
