name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Si no tienes build, solo copia los archivos
    - name: Prepare static preview folder
      run: |
        mkdir -p preview
        cp meta.json preview/
        cp -r blueprints preview/
        echo "<h1>Preview for PR #${{ github.event.pull_request.number }}</h1>" > preview/index.html


      # Despliega el preview usando el action
      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: preview
