name: PR Preview Static Files

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4

      - name: Deploy preview to gh-pages (pr-<NUM>)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # 👈 O solo blueprints/ si prefieres
          destination_dir: pr-${{ github.event.pull_request.number }}

      - name: Comment PR with Preview URL
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🚀 PR Preview deployed!
            👉 [View it here](https://dokploy.github.io/templates/pr-${{ github.event.pull_request.number }}/)
